### ISSUE TITLE
'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by KaioGomesx** [vimalloc/flask-jwt-extended#377]
my code:

```
from flask_jwt_extended import create_access_token, get_jwt_identity, jwt_required
from flask_restful import Resource, reqparse
from datetime import datetime, timedelta
from flask import current_app, request
import hashlib, uuid

class Auth(Resource):
    def post(self):
        # Validation
        try:
            parser = reqparse.RequestParser()
            parser.add_argument('username', type=str, required=True, location='json')
            parser.add_argument('password', type=str, required=True, location='json')
            body = parser.parse_args()
        except:
            return {
                "status": False,
                "message": "Fill in all fields."
            }, 400
        
        # Hashing to Password
        password_hashed = hashlib.sha1(body['password'].encode('utf-8')).hexdigest()

        # Get mongo instance
        mongo = current_app.config['mongo']

        # Select collection
        collection = mongo['****']['****']

        # Find to user
        user_document = collection.find({
            "username": body['username'],
            "password": password_hashed
        })

        # Count User
        if bool(user_document.count()):
            # Select access token collection
            token_collection = mongo['****']['*****']

            # Generate token
            token = uuid.uuid4()

            # Mount document
            document = {
                "access_token": token,
                "username": body['username'],
                "created_at": datetime.now().isoformat(),
                "expire_in": (datetime.now() + timedelta(hours=1)).isoformat()
            }

            # Save token
            token_collection.insert_one(document)

            # Create JWT Token
            jwt_token = create_access_token(token, expires_delta=False)

            # Returns
            return {
                "status": True,
                "access_token": jwt_token
            }, 200
        else:
            # Returns error
            return {
                "status": False,
                "message": "Username or password is wrong."
            }, 200
```

Error: 

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/usr/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/usr/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/kaiogomesx/italtel/reactStreex/backend/resources/platform/auth.py", line 56, in post
    jwt_token = create_access_token(token, expires_delta=False)
  File "/usr/lib/python3.7/site-packages/flask_jwt_extended/utils.py", line 173, in create_access_token
    headers=headers)
  File "/usr/lib/python3.7/site-packages/flask_jwt_extended/jwt_manager.py", line 522, in _create_access_token
    headers=headers
  File "/usr/lib/python3.7/site-packages/flask_jwt_extended/tokens.py", line 77, in encode_access_token
    json_encoder=json_encoder, headers=headers)
  File "/usr/lib/python3.7/site-packages/flask_jwt_extended/tokens.py", line 30, in _encode_jwt
    json_encoder=json_encoder, headers=headers).decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by KaioGomesx** [comment]
fix when i upgrade version to 3.25.0
